apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ooic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ooic
    app.kubernetes.io/part-of: byoc-app-zdwm
  name: ooic
spec:
  rules:
  - host: ooic-byoc-xxrp-tenant.apps.rhtap-ocp-4-12-amd64-us-east-2-lp7s6.ci.stonesoupengineering.com
    http:
      paths:
      - backend:
          service:
            name: ooic
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
